version: '3.8'
services:
  api_server:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "1992:1992"
    volumes:
      - ${SRC_HOST}:${SRC_CONTAINER}:rw

  db:
    container_name: chat_db
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "1993:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASS}
