version: '3.8'
services:
  api_server:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "1992:1992"
    volumes:
      - ./build:/home/node/chat_api/src:rw

  db:
    container_name: chat_db
    image: mongo:latest
    restart: always
    ports:
      - "1993:27017"
