version: '3.8'
services:
  api_server:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "1992:1992"
    volumes:
      - ./build:/home/node/chat_app/src:ro